ARG BASE_IMAGE="ghcr.io/gbraad-devenv/centos/dotfiles"
ARG BASE_VERSION="stream9"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/centos-golang"

USER root

RUN dnf install -y --setopt=tsflags=nodocs \
        delve \
        golang \
        golang-bin \
    && dnf clean all \
    && rm -rf /var/cache/yum
