ARG BASE_IMAGE="ghcr.io/gbraad-devenv/centos-golang/base"
ARG BASE_VERSION="stream9"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/centos-golang"

USER gbraad

ENTRYPOINT [ "/bin/zsh" ]